apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostservice-deploy
spec:
  selector:
    matchLabels:
      app: hostservice
  template:
    metadata:
      labels:
        app: hostservice
    spec:
      containers:
      - name: hostservice-container
        images: 3500ml/node-app:67fd7f3f68a1adc747cfb7c78a371a791e0b9213
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080